######################################
#### manual configuration example: ###
#Twitter:
#  access_token: XXX-XXX
#  access_token_secret: XXX
#  consumer_key: XXX
#  consumer_secret: XXX
#
#Discord:
#  - IncludeReplyToUser: false
#    IncludeRetweet: false
#    IncludeUserReply: true
#    custom_message: 'A new tweet!'
#    keyword_sets:
#    - - 'League'    # tweet will be posted if tweet contains all 3 words {League of Legends}, no particular order.
#      - 'of'
#      - 'Legends'
#    - - 'Dota 2'    # tweet will be posted if tweet contains 'Dota 2' in this specific order
#    - - 'MOBA'      # tweet will be posted if it contains 'MOBA'
#    twitter_ids:
#    - '123'         # define as many as you want with a dash {-} at the beginning
#    - '456'
#    twitter_handles:
#    - 'discordapp'
#    twitter_lists:
#    - 'https://twitter.com/rokxx/lists/dota-2'
#    webhook_urls:
#    - 'https://discordapp.com/api/webhooks/123456/XXXX-XXXX'
######################################

# configuration through environment variables
Twitter:
  access_token: '30394711-WcGfTgbimpWGkrZwOG1h83wlKHrBB6Xc7hWZtZpOW'
  access_token_secret: '5X88YOfeFAlM1RQiqkdVJMFGPZjT4W3eCLhRIwidBgEQc'
  consumer_key: 'qHa4d8CJEcgRmX45y7YJSc9HW'
  consumer_secret: 'BE3XnxMIZh7zGLzYeglFf2pBCUsEYBFBusCFKTgTmzTAyoYGCh'

Discord:
  - IncludeReplyToUser: false
    IncludeRetweet: true
    IncludeUserReply: false
    twitter_ids: ['136136326']
    webhook_urls: ['https://discord.com/api/webhooks/724064813348552814/UZDpgaiilM5UFGVFLfEFBEZ0Iw5848_2butMPclDBb_7qjXJLqJHJ6D1U__xb1Jb2kpQ']

  - IncludeReplyToUser: false
    IncludeRetweet: true
    IncludeUserReply: false
    twitter_ids: ['55395551']
    webhook_urls: ['https://discord.com/api/webhooks/724064729512804406/t6C4hun2mufn7-WUtxmS6Jsa3FKbelNuJEcNJpJ4GaCa6ZPd5c7GMJ1D-QCaNe5c_HqZ']

  - IncludeReplyToUser: false
    IncludeRetweet: true
    IncludeUserReply: false
    twitter_ids: ['236953420']
    webhook_urls: ['https://discord.com/api/webhooks/724064020025311293/Cy_isjDlaTUL3dBVJC8qzWYNR8qApmrUdUbDG5t5VJWi4KrWFAUSiiNSyUMtUCsf8G0W']
    
  - IncludeReplyToUser: false
    IncludeRetweet: true
    IncludeUserReply: false
    twitter_ids: ['26538229']
    webhook_urls: ['https://discord.com/api/webhooks/724063903968919583/H7iQn6kVj7ClqAdKZ-MAnO03yIzZAmBH4tFhmC15VlvcX1O1kMEnrOyKEMIhqlJ-coCg']

  - IncludeReplyToUser: false
    IncludeRetweet: true
    IncludeUserReply: false
    twitter_ids: ['326315947']
    webhook_urls: ['https://discord.com/api/webhooks/724063810058453063/7R44bh29YBv-prBZjf7jSP4W4flfASMriydb-Je9QcpjdAuhNhn9_IDhFqJpnFkxVvwp']

  - IncludeReplyToUser: false
    IncludeRetweet: true
    IncludeUserReply: false
    twitter_ids: ['25073877']
    webhook_urls: ['https://discord.com/api/webhooks/724063720841543710/SJeqT83Mi5jhnF-G7VipsGzsdhm0njOQSsH9djs0kCDYzbOguPxMRrO84ssX2_ygQc6h']

  - IncludeReplyToUser: false
    IncludeRetweet: true
    IncludeUserReply: false
    twitter_ids: ['44196397']
    webhook_urls: ['https://discord.com/api/webhooks/724063621209915412/LrVyfqB8qEPXnl0HC5KwfWwtI47ANsnHFE1BlhnxNG-NT4Fu70ef0veyZ5PoPLUJNaD5']

  - IncludeReplyToUser: false
    IncludeRetweet: true
    IncludeUserReply: false
    twitter_ids: ['1274397419896213505']
    webhook_urls: ['https://discordapp.com/api/webhooks/724044108032901270/t2tINrqtgLFj1jn_-QWTe1-ZI378JNBR-n--b4sryqb9e7Dq3AQ7CqWkVED_gs3e6u_m']
    
  - IncludeReplyToUser: false
    IncludeRetweet: true
    IncludeUserReply: false
    twitter_ids: ['30394711']
    webhook_urls: ['https://discord.com/api/webhooks/725092467262881862/mnZkQg-2xc4RZvHuiMjMJ4sDuz2NQPEAKbc1raBkVtAtAk5Mq-dssLrTflzBfyNYN_KD']

  - IncludeReplyToUser: ${INCLUDE_REPLY_TO_USER_9!b}
    IncludeRetweet: ${INCLUDE_RETWEET_9!b}
    IncludeUserReply: ${INCLUDE_USER_REPLY_9!b}
    custom_message: ${CUSTOM_MESSAGE_9}
    keyword_sets: ${KEYWORDS_9!ll}
    blackword_sets: ${BLACKWORDS_9!ll}
    twitter_ids: ${TWITTER_ID_9!l}
    twitter_handles: ${TWITTER_HANDLE_9!l}
    twitter_lists: ${TWITTER_LIST_9!l}
    track: ${TRACK_9!l}
    location: ${LOCATION_9!fl}
    webhook_urls: ${WEBHOOK_URL_9!wh}

  - IncludeReplyToUser: ${INCLUDE_REPLY_TO_USER_10!b}
    IncludeRetweet: ${INCLUDE_RETWEET_10!b}
    IncludeUserReply: ${INCLUDE_USER_REPLY_10!b}
    custom_message: ${CUSTOM_MESSAGE_10}
    keyword_sets: ${KEYWORDS_10!ll}
    blackword_sets: ${BLACKWORDS_10!ll}
    twitter_ids: ${TWITTER_ID_10!l}
    twitter_handles: ${TWITTER_HANDLE_10!l}
    twitter_lists: ${TWITTER_LIST_10!l}
    track: ${TRACK_10!l}
    location: ${LOCATION_10!fl}
    webhook_urls: ${WEBHOOK_URL_10!wh}
